### ISSUE TITLE
Fixing binary operator space.

### ISSUE THREAD

**Issue by tinesubic** [MikroMan/dragon_hack#1]
vmesnik.js : add spaces in beteen binary operators like =, +, comparisons...

**Comment by ActoreX** [comment]
Here is slightly changed code - if you haven't changed it already :)
https://github.com/MikroMan/dragon_hack/tree/fixing-binopt-space

**Comment by tinesubic** [comment]
Aleks, the current GUI in development is on GUI_test branch, not on master ;)
Deleting fixing-binopt-space branch.

**Comment by tinesubic** [comment]
Fixed.
