### ISSUE TITLE
checkCooki, variable uninitialized?

### ISSUE THREAD

**Issue by tinesubic** [MikroMan/dragon_hack#7]
Infunction checkCookie, line 71 of vmesnik.js. Is variable user initialized?

![image](https://cloud.githubusercontent.com/assets/6595139/8821483/421a8990-305e-11e5-8767-2b4a46e3251c.png)

**Comment by zigacernigoj** [comment]
Issue resolved. Context info: checkCookie and other functions related with cookies were changed a lot. Variables still need to be renamed -> named properly. So I'm opening new issue "Revise cookie implementation".
